---
- hosts: server
  remote_user: admin
  gather_facts: yes
  connection: ssh
  tasks:
      - name: create dir
        shell: |
                cd /home
                mkdir nomuk
                
      - name: ensure
        file:
          path: /home/nomuk
          state: directory

      - name: create file
        shell: |
                cd /home/nomuk
                echo "Hello, this is some text." > filename.txt