---
- hosts: server
  remote_user: admin
  become: true
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  vars:
    ansible_become_pass: "mbank2022"
  tasks:
      - name: create dir
        shell: |
                cd /home
                mkdir nomuk