---
- hosts: server
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  tasks:
      - name: create dir
        shell: |
                cd /home
                mkdir /home/nomuk