---
- hosts: server
  remote_user: admin
  become: yes
  connection: ssh
  tasks:
      - name: create dir
        shell: |
                cd /home
                mkdir /home/nomuk
      - name: create file
        shell: |
                cd /home/nomuk
                echo "Hello, this is some text." > filename.txt
